### ISSUE TITLE
Adding custom font ttf/woff/svg/eot/woff2

### ISSUE THREAD

**Issue by squall-cuckoo** [workco/marvin#63]
First of all great boilerplate i must say.

Made some adjustment from my end,
may I ask how am I able to add custom fonts?
Do I need to adjust the webpack?

**Comment by Stanko** [comment]
Hello @squall-cuckoo,

Adding fonts is easy, just add another rule to [shared rules](https://github.com/workco/marvin/blob/master/webpack/config.js#L75):

```js
// Fonts
{
  test: /\.(eot|ttf|woff|woff2)$/,
  include: paths.fonts, // don't forget to define this one
  use: 'file-loader?name=assets/[name]-[hash].[ext]',
},
```

File loader is already included within Marvin.

Cheers!

**Comment by Stanko** [comment]
https://github.com/workco/marvin/pull/65

**Comment by Fatal1stZ** [comment]
I used to declare some scss variables in app.scss.

And then trying to use these variables in my component (i've made import of app.scss in component's style.scss).
So, in developement mode it works fine, but when i try to build it into production, i've got an error about webpack cannot resolve my fonts.

`ModuleNotFoundError: Module not found: Error: Can't resolve './fonts/OpenSans/OpenSans-Bold.ttf' in 'C:\Develop\MyProject\dev\source\js\components\Form'`

To work with relative paths i've used resolve-url-loader, after css-loader.
```
  const sassLoaders = [
    {
      loader: 'css-loader',
      options: {
        sourceMap: IS_DEVELOPMENT,
        minimize: IS_PRODUCTION,
      },
    },
    {
      loader: 'resolve-url-loader',
      options: {
        sourceMap: IS_DEVELOPMENT,
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        sourceMap: IS_DEVELOPMENT,
        plugins: () => [
          autoprefixer(autoprefixerOptions),
        ],
      },
    },
    {
      loader: 'sass-loader',
      options: { sourceMap: IS_DEVELOPMENT },
    },
  ];
```
And how i load fonts.
```
  {
    test: /\.(woff|woff2|eot|ttf)$/,
    use: [
      {
        loader: 'file-loader',
        options: {
          name: 'client/assets/[name].[ext]',
        },
      },
    ],
    include: paths.fonts,
  },
```

Any idea how to handle it?

**Comment by Fatal1stZ** [comment]
Could you add pls an example of importing fonts to the repo?
I see, there is a mock for it.

I'd like to add some fonts to vars (e.g. $font-regular: "OpenSans";) and use it in my custom component with separate style file in component folder.

But i got an error Can't resolve '../assets/fonts/OpenSans/OpenSans-Regular.ttf' in 'C:\Develop\Marvin\source\js\components\global'

**Comment by Stanko** [comment]
Hello @Fatal1stZ, new version of marvin is not using SCSS but PostCSS, so you must be using an older version. I'll copy-paste how I handled fonts in an actual app that was made using older marvin.

`source/scss/app.scss`

```css
@import "base/fonts";
```

`source/scss/base/_fonts.scss`

```css
@font-face {
  font-family: 'Maison Neue';
  src: url('../assets/fonts/MaisonNeue-Light.eot');
  src: url('../assets/fonts/MaisonNeue-Light.eot?#iefix') format('embedded-opentype'),
    url('../assets/fonts/MaisonNeue-Light.woff2') format('woff2'),
    url('../assets/fonts/MaisonNeue-Light.woff') format('woff'),
    url('../assets/fonts/MaisonNeue-Light.ttf') format('truetype');
  font-weight: 200;
  font-style: normal;
}
/* more @font-face definitions */
```

And in `source/js/client.js`

```js
// Load SCSS
import '../scss/app.scss';
```

webpack config: 
```js
  // Fonts
  {
    test: /\.(eot|ttf|woff|woff2)$/,
    include: path.join(__dirname, './source/assets/fonts'),
    use: 'file-loader?name=assets/[name]-[hash].[ext]',
  },
```

Your problem seems to be `resolve-url-loader` and unfortunately I have never used it, so I'm not able to help with it.

Hope this helps!
